### ISSUE TITLE
Unable to update search index

### ISSUE THREAD

**Issue by htollefsen** [netgen/TagsBundle#23]
When I try to update the elasticsearch index the following error occurs when trying to index content with an eztags fieldtype: **No type registered for eztags**

### Steps to reproduce
1. Install TagsBundle in a fresh eZPublish installation (5.4+), and create a populate values into any contenttype with an eztags fieldtype.
2. Install elasticsearch and enable EzPublishElasticsearchBundle
3. Run ```php ezpublish/console ezpublish:elasticsearch_create_index``` from document root
4. The error appears on the first eztag it tries to index

**Comment by emodric** [comment]
Hi!

I haven't implemented indexing handlers for `eztags` field type yet, since the implemenatation is not complete yet (AFAIK, please correct me if I'm wrong).

There was a pull request #20 recently that activated the search capability in the field type, but without implementing handlers. Can you check if removing `isSearchable` method from field type fixes your problem?

**Comment by htollefsen** [comment]
> ...the implemenatation is not complete yet

I am not sure of this, myself, but it makes sence regarding the missing documentation (atleaset I had a hard time finding one.

> Can you check if removing isSearchable method from field type fixes your problem?

I removed ```isSearchable``` from Netgen\TagsBundle\Core\FieldType\Tags\Type.php but the result were the same.

**Comment by emodric** [comment]
> I removed isSearchable from Netgen\TagsBundle\Core\FieldType\Tags\Type.php but the result were the same.

Alright, thanks for testing. In that case, I have no idea how to fix this issue yet :(

**Comment by htollefsen** [comment]
I'm just throwing this out there, as I'm pretty fresh to FieldType implementations in eZPublish 5, but isn't the FieldType missing a an implementation of [FieldStorage for the SPI](https://doc.ez.no/display/EZP/Field+Type+API+and+best+practices#FieldTypeAPIandbestpractices-Storingexternaldata)?

**Comment by emodric** [comment]
@htollefsen Hm... I'll look into it, thanks!

**Comment by htollefsen** [comment]
@emodric FYI, I don't know how I missed [the documentation](https://doc.ez.no/display/EZP/Configure+Search+Engines+Bundles) or if it has just been made public today, but I clearly had some missconfigurations that might be the cause my issue. I'll test again soon with proper configs.

**Comment by emodric** [comment]
Hi @htollefsen 

This issue is fixed in https://github.com/netgen/TagsBundle/commit/6e331f1b82ce9cf343eba8d5f704304d0e8994d5.

I marked the `eztags` field type as unindexable for now. Feel free to create a new enhancement issue in order to implement `eZ\Publish\SPI\FieldType\Indexable` interface in the field type :)
