### ISSUE TITLE
getRelatedContent should support ordering and criterion

### ISSUE THREAD

**Issue by wizhippo** [netgen/TagsBundle#26]
I believe getRelatedContent should support ordering and criterion.  The use case of ordering should be obvious.  I also see the use case of only wanting to return related content based on criterion.  

I was thinking adding changing it to public function getRelatedContent( Tag $tag, $offset = 0, $limit = -, $order, sortClauses = null, $criterion = null);

This change would also need to be reflected in the pagerfanta.

What do you think?

**Comment by emodric** [comment]
Hi @wizhippo,

the purpose of that method from start was to return unordered list of related content. Since the content can be distributed throughout the whole eZ database, it doesn't really have sense to employ sorting and filtering.

What you want can be achieved with eZ search APIs and `TagId` and `TagKeyword` criteria.

**Comment by wizhippo** [comment]
That's too simple.  Thanks.

**Comment by emodric** [comment]
> That's too simple. Thanks.

Care to elaborate? :)

**Comment by wizhippo** [comment]
For some reason I forgot that that a tag is just another field type and I was looking at the tagservice to do it all.  Silly me.

**Comment by emodric** [comment]
Ah, OK :) I'm glad it's working for you :)
