### ISSUE TITLE
Add the abbility to add a translation via ui

### ISSUE THREAD

**Issue by wizhippo** [netgen/TagsBundle#46]
Translations are visible but no way to add additional translations via the ui.

![image](https://cloud.githubusercontent.com/assets/1456102/21996767/c8feba24-dbf9-11e6-89d9-8e2defb47bba.png)

**Comment by emodric** [comment]
Note to self: Currently, new translations can be added by editing the tag, but only if the default siteaccess is configured with all translations that we want to use.

We need to make the list of used languages configurable to be based on language service instead of siteaccess languages.

**Comment by wizhippo** [comment]
@emodric I have tried this with configured languages in the default site access.  When creating a tag the options of what language to use displays with all the available languages.  After creating the tag I cannot add a new translation to the existing tag in another language.  The is no add translation nor during the edit process does it ask or allow to

https://youtu.be/OnyGDtq9u8A

**Comment by wizhippo** [comment]
Can't believe I missed the giant blue "Edit Tag"button.  Clicking this bring up the option to select the language.  Guess I was just expecting this to be under the translations tab.

**Comment by emodric** [comment]
@wizhippo I'm not against reorganizing the interface to be more clear :)

Current implementation is, for the most part, copy of legacy eZ Tags admin which can ofcourse be improved.

**Comment by solene2a** [comment]
Hello
I installed the tagsbundle 3.0.8 and I can't add translations on my tags. 
I don't understand what I have to do to activate the others languages in the admin UI. 
Can you help me please ? 
Thanks

**Comment by emodric** [comment]
@solene2a Your siteaccess needs to have multiple languages configured in its language list. Once this is done, you can click on the blue "Edit tag" button, and then you will get the list of already existing translations as well as the list of translations to add.

Does that answer your question?

**Comment by solene2a** [comment]
Thank you, but can you tell me where do I have to put the languages list, is it in the ezplaform.yml, in ezpublish -> system parts ? 
I have something like 
`
ezpublish:

    # Siteaccess configuration, with one siteaccess per default
    siteaccess:
        list: [site, eng, it]
        groups:
            site_group: [site, eng, it]
        default_siteaccess: site
        match:
            URIElement: 1

    # System settings, grouped by siteaccess and/or siteaccess group
    system:
        site_group:
            translation_siteaccesses: [site, eng, it]
        site:
            languages: [fre-FR, ita-IT, eng-GB]
        eng:
            languages: [eng-GB, fre-FR]
        it:
            languages: [ita-IT, fre-FR, eng-GB]
`

and it doesn't work...

**Comment by emodric** [comment]
@solene2a Good to hear that :)

**Comment by solene2a** [comment]
Hello it's me again ;-)
I have another problem with the translations : I can't put all the languages availables in my default siteaccess, because in my website if there is a missing translation, the content must not be displayed.
Is it possible to think about another way to get the language list ? To add another parameter elsewhere for example... It will be great.
Thank you

**Comment by emodric** [comment]
I'm afraid no, not really. This would complicate configuration and maintenance of site configuration in regards to languages and tags and I think it would bring more problems than benefit.

Besides that, since the new eZ Platform Admin UI is running within its own siteaccess, it is expected that languages configuration is automatically propagated to Netgen Tags.

I presume that the issue comes from eZ Platform UI running in the default siteaccess, yes? That was/is a core design problem of eZ Platform UI which is not easily solved, I know. If you think there might be a way to have both options (automatically use languages configured in eZ, but be able to override on demand), I would be okay to merge it as a fix specific to eZ Platform UI.

**Comment by solene2a** [comment]
Thank for your answer. 
We are going to install the new eZPlatform Admin UI, I think it will solve our problems. I will let you know ! 
Regards
