### ISSUE TITLE
Error when in edit-view

### ISSUE THREAD

**Issue by skonrad** [netgen/TagsBundle#54]
Hi everyone,

tonight i was testing you bundle with my project.

While the system seemed fine after after adding db, routing and the two bundles (`EzCoreExtraBundle` and `NetgenTagsBundle`). I can add the field-type to a type. (That's working with the current platform-release `1.8.0`)

Maybe you guys got a clue if i'm doing something wrong.

Thanks in advance.

# Errors

## JavaScript

When i select another selection-mode than `Default` the system does seem to act in unexpected ways.
I constantly get `Uncaught TypeError: EzTags[builder] is not a constructor` within the JS-Console (Chrome@56.0.2924.87).

When I let the type use the `Default` at "Edit view", I can't figure out how to get existing tags to the list.

## PHP/Twig

When opening the tags-administration (`/ez#/tags/tags%2Fadmin%2F`) i get the following error:
```
An exception has been thrown during the rendering of a template ("Warning: Cannot bind closure to scope of internal class stdClass").
```
this error is thrown at `/var/www/vendor/netgen/tagsbundle/Resources/views/admin/tag/dashboard.html.twig:1`
`/var/www/vendor/twig/twig/lib/Twig/Template.php:364`
`/var/www/vendor/lolautruche/ez-core-extra-bundle/Templating/Twig/DebugTemplate.php:51`

# SystemSpecs
PHP-Version: 7.1
MariaDB-Version: 10.0
Solr-Version: 4.10.4

**Comment by emodric** [comment]
Hi @skonrad !

About the first issue (error in JavaScript console), maybe I should've mentioned in the docs that no edit views other than `Default` are supported yet in Platform UI field edit interface. As for adding tags to the list in `Default` edit view, there's an autocomplete input field that you can use to search for tags and add them to the field.

As for PHP/Twig error, it could be due to using versions of packages not suitable for your version of PHP. I ran into the same error message before and solution was to upgrade `ocramius/proxy-manager` (https://github.com/ezsystems/ezpublish-kernel/pull/1880)

**Comment by skonrad** [comment]
Hi @emodric 

thanks for the quick response.

Regarding the JS-Error it makes sence that it doesn't work if it's not implemented yet. :)
For the `Default`-Version I just checked and it works. My co-workers say it is intuitive (so it's probably my fault for not recognizing the functionality at first). The hint for the suggest really helped me though.

In respect of the twig/php-error it seems like i accidently updated twig to 2.x (since the limitation is not given in ezplatform itself). After downgrading to the latest 1.x-release of twig, it's working fine again.

Got all my issues resolved now. Thanks for the help. Love the bundle so far.

**Comment by emodric** [comment]
@skonrad I've added a not about `Default` edit view being the only one: https://github.com/netgen/TagsBundle/commit/92fbd4c393c9deaee2a75f8fa85adcd808b5ed4e
